### ISSUE TITLE
Error while running the program

### ISSUE THREAD

**Issue by nithiyadavis** [abitran/opencv_transition#1]
what is this error and how can i solve it?
error: OpenCV(3.4.2) C:\projects\opencv-python\opencv\modules\core\src\arithm.cpp:659: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'cv::arithm_op'

**Comment by abitran** [comment]
Hi... check that the images you are processing have the same number of channels.
